[package]
name = "qbmr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
figment = { version = "0.10.6", features = ["toml", "env"] }
path-absolutize = "3.0.11"
