[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flexi_logger = "0.19.6"
log = "0.4.14"
time = "0.3.4"
serde = "1.0.130"
serde_json = "1.0"